name: Build and Push Grafana Docker Image

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          docker system prune -a -f

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build Docker image using Makefile
        run: docker build -t grafana-rm -f Dockerfile .

      - name: Push Docker image
        run: |
          docker tag grafana-rm ${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm
