name: Build and Push Grafana Docker Image

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/grafana-rm:buildcache,mode=max